/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.wget.hepl.ds.doctorclientapplication;

import be.wget.hepl.ds.entitiesdataobjects.Analysis;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wget
 */
public class AnalysisSelectorGui extends javax.swing.JDialog {

    private ArrayList<Analysis> analyses;
    private ArrayList<Analysis> selectedAnalysis;
    private boolean isUrgent;
    private boolean isCancelled;
    
    /**
     * Creates new form AnalysisSelectorGui
     */
    public AnalysisSelectorGui(Frame parent, ArrayList<Analysis> analyses) {
        super(parent, true);
        initComponents();
        this.setLocationRelativeTo(parent);
        
        this.analyses = analyses;
        this.setLocationRelativeTo(parent);
        
        this.selectedAnalysis = new ArrayList<>();
        this.isUrgent = false;
        this.isCancelled = false;
        
        DefaultTableModel analysisTableModel =
            (DefaultTableModel)this.analysisTable.getModel();
        for (int i = 0; i < this.analyses.size(); i++) {
            analysisTableModel.addRow(new Object[] {
                this.analyses.get(i).getId(),
                this.analyses.get(i).getItem(),
                this.analyses.get(i).getUnit(),
                false});
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        availableAnalysesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        analysisTable = new javax.swing.JTable();
        isUrgentCheckbox = new javax.swing.JCheckBox();
        sendButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        availableAnalysesLabel.setText("Select the analysis you want to perform:");

        analysisTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Item", "Unit", "Select"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(analysisTable);

        isUrgentCheckbox.setText("Is urgent");

        sendButton.setText("Ask for selected analysis");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(availableAnalysesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(isUrgentCheckbox)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(availableAnalysesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(isUrgentCheckbox)
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        DefaultTableModel analysisTableModel = (DefaultTableModel) this.analysisTable.getModel();
        for (int i = 0; i < analysisTableModel.getRowCount(); i++) {
            if (!(Boolean)analysisTableModel.getValueAt(i, 3)) {
                continue;
            }
            this.selectedAnalysis.add(this.analyses.get(i));
        }
        
        this.isUrgent = this.isUrgentCheckbox.isSelected();
        
        this.setVisible(false);
    }//GEN-LAST:event_sendButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.isCancelled = true;
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    public ArrayList<Analysis> getSelectedAnalyses() {
        return this.selectedAnalysis;
    }
    
    public boolean isUrgent() {
        return this.isUrgent;
    }
    
    public boolean hasBeenCancelled() {
        return this.isCancelled;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable analysisTable;
    private javax.swing.JLabel availableAnalysesLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox isUrgentCheckbox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables
}
